/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef spell_correction_CONSTANTS_H
#define spell_correction_CONSTANTS_H

#include "spell_correction_types.h"

namespace Adingo {

class spell_correctionConstants {
 public:
  spell_correctionConstants();

};

extern const spell_correctionConstants g_spell_correction_constants;

} // namespace

#endif
