/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "spell_correction_constants.h"

namespace Adingo {

const spell_correctionConstants g_spell_correction_constants;

spell_correctionConstants::spell_correctionConstants() {
}

} // namespace

