/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "test_constants.h"

namespace Test {

const testConstants g_test_constants;

testConstants::testConstants() {
}

} // namespace

