/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "ttydic_constants.h"

namespace Jingoo {

const ttydicConstants g_ttydic_constants;

ttydicConstants::ttydicConstants() {
}

} // namespace

