/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef ttydic_CONSTANTS_H
#define ttydic_CONSTANTS_H

#include "ttydic_types.h"

namespace Jingoo {

class ttydicConstants {
 public:
  ttydicConstants();

};

extern const ttydicConstants g_ttydic_constants;

} // namespace

#endif
