/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xodus;

import static org.junit.Assert.*;

public class TestTest {
    @org.junit.Test
    public void someLibraryMethodReturnsTrue() {
        Test classUnderTest = new Test();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
