name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: tag number
        run: echo ${{ github.event.release.tag_name }}

      - name: event ref
        run: echo ${{ github.event.ref }}

      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo ::set-output name=version::${VERSION}

      - name: print
        run: echo ${{ steps.version.outputs.version }}
